### ISSUE TITLE
[BUG] Link underlined when textDecoration "none" and href defined

### ISSUE THREAD

**Issue by guidobotta** [TiendaNube/nimbus-design-system#64]
🐛 **Describe the bug**

Component Link keeps underlined when textDecoration in "none" but href is defined

🧐 **To Reproduce**

Create a Link like this:

```jsx
<Link textDecoration="none" href="mailto: hola@tiendanube.com">
  hola@tiendanube.com
</Link>
```

There's a sandbox example: https://codesandbox.io/s/strange-ben-8i3b3h?file=/src/App.tsx

✅ **Expected behavior**

Expect not to be underlined when textDecoration prop is "none"

❗️ **Additional context**

The problem could be here

<img width="456" alt="Captura de Pantalla 2022-12-13 a la(s) 12 57 17" src="https://user-images.githubusercontent.com/43834276/207383822-bf01b82f-591c-4a59-bf9f-7fda1ef1bdbd.png">

**Comment by juniorconquista** [comment]
@guidobotta estou iniciando as trativas dessa issue.

**Comment by juniorconquista** [comment]
@guidobotta first of all, thank you very much for your contribution in reporting this bug and for the organization and information put into the issue.

Thanks to this, the resolution of the problem was much faster.

In your sandbox I made the correction by updating the `@nimbus-ds/link` package to the `2.1.1` version which already contains the mentioned bug resolution: https://codesandbox.io/s/strange-ben-8i3b3h?file=/src/App.tsx

**Comment by guidobotta** [comment]
Great! Thank you @juniorconquista!
